"""
Phase 10 — Timm (2014) self-citation test.

Timm (2014) and Timm & Schinner (2020) propose that the Voynich text was
generated by copying words from nearby text and modifying them (glyph swap,
addition, deletion, concatenation). No cipher, no language — just copying.

Bold claim: "We are not aware of any statistical property of the VMS that
qualitatively contradicts our proposed self-citation algorithm."

This module tests:

  Part 1 — Self-citation signatures in the real manuscript:
    10a: Proximity clustering (Timm claims 91% of similar words within 3 lines)
    10b: Vocabulary similarity decay with line distance
    10c: Page-local vocabulary (adjacent pages share more words?)
    10d: First-word repetition rate

  Part 2 — Structural falsification:
    10e: Simplified self-citation generator vs 4 confirmed structural properties
         (same framework as Phase 9f)

References:
  Timm, T. (2014). arXiv:1407.6639
  Timm, T. & Schinner, A. (2020). Cryptologia, 44(1), 22-42.
  GitHub: TorstenTimm/SelfCitationTextgenerator

Output:
  timm_test.json
  timm_test_summary.txt
  DB table: timm_test
"""

from __future__ import annotations

import json
import random
import sqlite3
from collections import defaultdict
from pathlib import Path

import click
import numpy as np

from .config import ToolkitConfig
from .currier_line_test import parse_ivtff_lines
from .utils import print_header, print_step
from .word_structure import parse_eva_words


SEED = 42
N_NULL = 500
N_SYNTH = 50       # synthetic corpora for Part 2
MAX_EDIT_DIST = 2   # threshold for "similar" words in 10a
PROXIMITY_WINDOW = 3  # lines, as per Timm's claim

# 19 EVA characters
EVA_CHARS = list("acdefghiklmnopqrsty")


# =====================================================================
# Helpers
# =====================================================================

def _edit_distance(a: str, b: str) -> int:
    """Levenshtein edit distance."""
    if len(a) < len(b):
        return _edit_distance(b, a)
    if len(b) == 0:
        return len(a)
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a):
        curr = [i + 1]
        for j, cb in enumerate(b):
            cost = 0 if ca == cb else 1
            curr.append(min(curr[j] + 1, prev[j + 1] + 1, prev[j] + cost))
        prev = curr
    return prev[len(b)]


def _normalized_edit_dist(a: str, b: str) -> float:
    """Edit distance normalized by max word length."""
    max_len = max(len(a), len(b))
    if max_len == 0:
        return 0.0
    return _edit_distance(a, b) / max_len


def _jaccard(set_a: set, set_b: set) -> float:
    union = set_a | set_b
    if not union:
        return 0.0
    return len(set_a & set_b) / len(union)


def _z_score(observed: float, null_mean: float, null_std: float) -> float | None:
    if null_std < 1e-10:
        return None
    return (observed - null_mean) / null_std


# =====================================================================
# 10a — Proximity clustering
# =====================================================================

def test_proximity_clustering(lines: list[dict]) -> dict:
    """Timm's central claim: 91% of similar words are within 3 lines.

    For each word occurrence, find the nearest occurrence of a similar
    word (edit distance <= 2) and record the line distance.
    """
    # Build word occurrence index: word -> list of (global_line_idx)
    word_positions: dict[str, list[int]] = defaultdict(list)
    for i, line in enumerate(lines):
        for word in line["words"]:
            word_positions[word].append(i)

    # For efficiency: only consider words that appear 2+ times
    # and sample if too many types
    multi_types = [w for w, pos in word_positions.items() if len(pos) >= 2]

    # Exact-match proximity: fraction of repeated words within PROXIMITY_WINDOW
    n_within = 0
    n_total_pairs = 0
    for word in multi_types:
        positions = word_positions[word]
        for j in range(len(positions) - 1):
            dist = positions[j + 1] - positions[j]
            n_total_pairs += 1
            if dist <= PROXIMITY_WINDOW:
                n_within += 1

    exact_rate = n_within / max(1, n_total_pairs)

    # Edit-distance proximity: for each occurrence, find nearest similar
    # word (edit dist <= MAX_EDIT_DIST) and check if within window.
    # This is expensive, so sample up to 2000 word types.
    rng = random.Random(SEED)
    all_types = list(word_positions.keys())
    if len(all_types) > 2000:
        sample_types = rng.sample(all_types, 2000)
    else:
        sample_types = all_types

    n_edit_within = 0
    n_edit_total = 0
    for word in sample_types:
        positions = word_positions[word]
        # Find similar words (edit distance <= MAX_EDIT_DIST)
        for other_word, other_positions in word_positions.items():
            if other_word == word:
                continue
            if abs(len(other_word) - len(word)) > MAX_EDIT_DIST:
                continue
            ed = _edit_distance(word, other_word)
            if ed > MAX_EDIT_DIST:
                continue
            # For each pair of positions, check proximity
            for p1 in positions:
                # Find nearest position in other_positions
                # Binary search would be faster but positions are sorted
                min_dist = float("inf")
                for p2 in other_positions:
                    d = abs(p1 - p2)
                    if d < min_dist:
                        min_dist = d
                n_edit_total += 1
                if min_dist <= PROXIMITY_WINDOW:
                    n_edit_within += 1

    edit_rate = n_edit_within / max(1, n_edit_total)

    return {
        "exact_match_proximity_rate": round(exact_rate, 4),
        "exact_match_n_pairs": n_total_pairs,
        "edit_distance_proximity_rate": round(edit_rate, 4),
        "edit_distance_n_pairs": n_edit_total,
        "n_word_types": len(all_types),
        "n_multi_types": len(multi_types),
        "timm_claim": 0.91,
    }


def null_proximity_clustering(lines: list[dict], n_perms: int = N_NULL,
                               seed: int = SEED) -> dict:
    """Null: shuffle words within section, preserving line lengths."""
    rng = random.Random(seed)

    # Group lines by section (via folio -> section mapping)
    by_section: dict[str, list[int]] = defaultdict(list)
    for i, line in enumerate(lines):
        sec = line.get("section", "?")
        by_section[sec].append(i)

    null_exact_rates: list[float] = []

    for perm_i in range(n_perms):
        # Shuffle words within each section
        shuffled_words: dict[int, list[str]] = {}
        for sec, line_indices in by_section.items():
            all_words = []
            line_lengths = []
            for idx in line_indices:
                words = lines[idx]["words"]
                all_words.extend(words)
                line_lengths.append(len(words))

            rng.shuffle(all_words)

            pos = 0
            for idx, length in zip(line_indices, line_lengths):
                shuffled_words[idx] = all_words[pos:pos + length]
                pos += length

        # Measure exact-match proximity on shuffled
        word_pos: dict[str, list[int]] = defaultdict(list)
        for i in range(len(lines)):
            for word in shuffled_words.get(i, []):
                word_pos[word].append(i)

        n_within = 0
        n_total = 0
        for positions in word_pos.values():
            if len(positions) < 2:
                continue
            for j in range(len(positions) - 1):
                dist = positions[j + 1] - positions[j]
                n_total += 1
                if dist <= PROXIMITY_WINDOW:
                    n_within += 1

        null_exact_rates.append(n_within / max(1, n_total))

    return {
        "null_mean": round(float(np.mean(null_exact_rates)), 4),
        "null_std": round(float(np.std(null_exact_rates, ddof=1)), 6),
    }


# =====================================================================
# 10b — Vocabulary similarity decay
# =====================================================================

def test_similarity_decay(lines: list[dict], max_distance: int = 20) -> dict:
    """Measure vocabulary similarity (Jaccard) between lines at distance d.

    If self-citation: similarity decays with distance.
    """
    # Build line vocabularies
    line_vocabs = [set(line["words"]) for line in lines]
    n_lines = len(line_vocabs)

    # Compute mean Jaccard at each distance
    distance_sims: dict[int, list[float]] = defaultdict(list)

    for i in range(n_lines):
        if not line_vocabs[i]:
            continue
        for d in range(1, min(max_distance + 1, n_lines - i)):
            j = i + d
            if not line_vocabs[j]:
                continue
            sim = _jaccard(line_vocabs[i], line_vocabs[j])
            distance_sims[d].append(sim)

    mean_by_distance = {}
    for d in range(1, max_distance + 1):
        sims = distance_sims.get(d, [])
        if sims:
            mean_by_distance[d] = round(float(np.mean(sims)), 6)

    # Compute correlation: distance vs similarity
    distances = []
    similarities = []
    for d, mean_sim in sorted(mean_by_distance.items()):
        distances.append(d)
        similarities.append(mean_sim)

    if len(distances) > 2:
        corr = float(np.corrcoef(distances, similarities)[0, 1])
    else:
        corr = None

    return {
        "mean_similarity_by_distance": mean_by_distance,
        "correlation_distance_similarity": round(corr, 4) if corr is not None else None,
        "sim_at_d1": mean_by_distance.get(1),
        "sim_at_d5": mean_by_distance.get(5),
        "sim_at_d20": mean_by_distance.get(20),
    }


# =====================================================================
# 10c — Page-local vocabulary
# =====================================================================

def test_page_local_vocab(pages: list[dict]) -> dict:
    """Compare vocabulary overlap between adjacent pages vs random pairs."""
    page_vocabs = [set(p["words"]) for p in pages if len(p["words"]) >= 10]
    n_pages = len(page_vocabs)

    if n_pages < 4:
        return {"skipped": True, "reason": "too few pages"}

    # Adjacent pairs
    adj_jaccards = []
    for i in range(n_pages - 1):
        j = _jaccard(page_vocabs[i], page_vocabs[i + 1])
        adj_jaccards.append(j)

    # Random pairs (same number as adjacent, for fair comparison)
    rng = random.Random(SEED)
    random_jaccards = []
    for _ in range(len(adj_jaccards)):
        i, j = rng.sample(range(n_pages), 2)
        random_jaccards.append(_jaccard(page_vocabs[i], page_vocabs[j]))

    adj_mean = float(np.mean(adj_jaccards))
    rand_mean = float(np.mean(random_jaccards))

    return {
        "adjacent_jaccard_mean": round(adj_mean, 4),
        "random_jaccard_mean": round(rand_mean, 4),
        "ratio": round(adj_mean / rand_mean, 4) if rand_mean > 0 else None,
        "n_adjacent_pairs": len(adj_jaccards),
    }


def null_page_local_vocab(pages: list[dict], n_perms: int = N_NULL,
                           seed: int = SEED) -> dict:
    """Null: shuffle page order within section, recompute adjacent Jaccard."""
    rng = random.Random(seed)

    # Group pages by section
    section_pages: dict[str, list[int]] = defaultdict(list)
    page_vocabs = []
    for i, p in enumerate(pages):
        if len(p["words"]) < 10:
            continue
        section_pages[p.get("section", "?")].append(len(page_vocabs))
        page_vocabs.append(set(p["words"]))

    n_pages = len(page_vocabs)
    if n_pages < 4:
        return {"null_mean": 0.0, "null_std": 0.0}

    null_ratios: list[float] = []

    for _ in range(n_perms):
        # Shuffle within section
        shuffled_order = list(range(n_pages))
        for sec, indices in section_pages.items():
            shuffled_indices = indices[:]
            rng.shuffle(shuffled_indices)
            for orig, shuf in zip(indices, shuffled_indices):
                shuffled_order[orig] = shuf

        # Adjacent pairs in shuffled order
        adj = []
        for i in range(n_pages - 1):
            adj.append(_jaccard(page_vocabs[shuffled_order[i]],
                                page_vocabs[shuffled_order[i + 1]]))

        # Random pairs
        rand = []
        for _ in range(len(adj)):
            a, b = rng.sample(range(n_pages), 2)
            rand.append(_jaccard(page_vocabs[a], page_vocabs[b]))

        adj_mean = float(np.mean(adj))
        rand_mean = float(np.mean(rand))
        ratio = adj_mean / rand_mean if rand_mean > 0 else 1.0
        null_ratios.append(ratio)

    return {
        "null_mean": round(float(np.mean(null_ratios)), 4),
        "null_std": round(float(np.std(null_ratios, ddof=1)), 6),
    }


# =====================================================================
# 10d — First-word repetition
# =====================================================================

def test_first_word_repetition(lines: list[dict], window: int = 3) -> dict:
    """Check if first word of a line repeats as first word in previous lines."""
    n_lines = len(lines)
    n_repeated = 0
    n_tested = 0

    for i in range(window, n_lines):
        first_word = lines[i]["words"][0] if lines[i]["words"] else None
        if first_word is None:
            continue
        n_tested += 1
        # Check previous 'window' lines
        for j in range(max(0, i - window), i):
            prev_first = lines[j]["words"][0] if lines[j]["words"] else None
            if first_word == prev_first:
                n_repeated += 1
                break

    rate = n_repeated / max(1, n_tested)

    return {
        "first_word_repetition_rate": round(rate, 4),
        "n_repeated": n_repeated,
        "n_tested": n_tested,
        "window": window,
    }


def null_first_word_repetition(lines: list[dict], window: int = 3,
                                n_perms: int = N_NULL,
                                seed: int = SEED) -> dict:
    """Null: shuffle first words across lines within page."""
    rng = random.Random(seed)

    # Group lines by folio
    by_folio: dict[str, list[int]] = defaultdict(list)
    for i, line in enumerate(lines):
        by_folio[line["folio"]].append(i)

    first_words = [line["words"][0] if line["words"] else "" for line in lines]

    null_rates: list[float] = []

    for _ in range(n_perms):
        shuffled_fw = first_words[:]
        for folio, indices in by_folio.items():
            fw_in_folio = [shuffled_fw[i] for i in indices]
            rng.shuffle(fw_in_folio)
            for idx, fw in zip(indices, fw_in_folio):
                shuffled_fw[idx] = fw

        # Measure repetition rate
        n_rep = 0
        n_test = 0
        for i in range(window, len(lines)):
            fw = shuffled_fw[i]
            if not fw:
                continue
            n_test += 1
            for j in range(max(0, i - window), i):
                if shuffled_fw[j] == fw:
                    n_rep += 1
                    break

        null_rates.append(n_rep / max(1, n_test))

    return {
        "null_mean": round(float(np.mean(null_rates)), 4),
        "null_std": round(float(np.std(null_rates, ddof=1)), 6),
    }


# =====================================================================
# 10e — Self-citation generator vs structural properties
# =====================================================================

def _modify_word(word: str, rng: random.Random) -> str:
    """Apply a random Timm-style modification to a word.

    50% glyph swap, 30% add/delete, 20% prefix modification.
    """
    if not word:
        return word

    r = rng.random()

    if r < 0.50:
        # Glyph substitution: replace one character
        if len(word) >= 1:
            pos = rng.randint(0, len(word) - 1)
            new_char = rng.choice(EVA_CHARS)
            word = word[:pos] + new_char + word[pos + 1:]

    elif r < 0.80:
        # Addition (15%) or deletion (15%)
        if rng.random() < 0.5 and len(word) > 1:
            # Delete one character
            pos = rng.randint(0, len(word) - 1)
            word = word[:pos] + word[pos + 1:]
        else:
            # Add one character
            pos = rng.randint(0, len(word))
            new_char = rng.choice(EVA_CHARS)
            word = word[:pos] + new_char + word[pos:]

    else:
        # Prefix modification: add/remove common prefix
        prefixes = ["d", "q", "o", "ch", "ok", "qo"]
        if rng.random() < 0.5:
            # Add prefix
            prefix = rng.choice(prefixes)
            word = prefix + word
        elif len(word) > 2:
            # Remove prefix if present
            for prefix in sorted(prefixes, key=len, reverse=True):
                if word.startswith(prefix):
                    word = word[len(prefix):]
                    break

    return word


def generate_self_citation_corpus(pages: list[dict], seed: int = SEED) -> list[dict]:
    """Generate a synthetic corpus using simplified self-citation.

    For each page:
    1. Seed with the first line of the real page
    2. For subsequent lines: copy words from previous 1-5 lines
    3. Apply random modifications
    4. Optionally add gallows prefix to paragraph-initial words (94%)
    """
    rng = random.Random(seed)
    simple_gallows = list("tkpf")

    synthetic_pages = []

    for page in pages:
        real_lines = page.get("line_words", [])
        if not real_lines:
            synthetic_pages.append({
                "section": page.get("section", "?"),
                "words": [],
                "line_words": [],
            })
            continue

        synth_lines: list[list[str]] = []

        # Seed with real first line
        synth_lines.append(list(real_lines[0]))

        for line_idx in range(1, len(real_lines)):
            target_len = len(real_lines[line_idx])
            if target_len == 0:
                synth_lines.append([])
                continue

            # Select source: previous 1-5 lines
            lookback = min(5, len(synth_lines))
            source_line_idx = rng.randint(
                len(synth_lines) - lookback, len(synth_lines) - 1
            )
            source_words = synth_lines[source_line_idx]

            if not source_words:
                # Fallback: use seed line
                source_words = synth_lines[0] if synth_lines[0] else ["daiin"]

            # Generate words by copying and modifying
            new_line: list[str] = []
            for w_idx in range(target_len):
                source_word = source_words[w_idx % len(source_words)]
                # 30% copy unchanged, 70% modify
                if rng.random() < 0.30:
                    new_word = source_word
                else:
                    new_word = _modify_word(source_word, rng)
                new_line.append(new_word)

            # Paragraph-initial: add gallows prefix (94% per Timm)
            # We approximate: first line of each page + every ~5th line
            if line_idx == 0 or (line_idx % 5 == 0 and rng.random() < 0.94):
                if new_line and not any(c in simple_gallows for c in new_line[0]):
                    glyph = rng.choice(simple_gallows)
                    new_line[0] = glyph + new_line[0]

            synth_lines.append(new_line)

        # Build page dict
        all_words = [w for line in synth_lines for w in line]
        synthetic_pages.append({
            "section": page.get("section", "?"),
            "words": all_words,
            "line_words": synth_lines,
        })

    return synthetic_pages


def _measure_structural_properties(pages: list[dict]) -> dict:
    """Measure the 4 key structural properties (same as Phase 9f)."""
    results = {}

    # 1. Line-end 'm' fraction
    m_total = 0
    m_line_final = 0
    for page in pages:
        for line in page.get("line_words", []):
            if not line:
                continue
            for word in line:
                m_total += word.count("m")
            last_word = line[-1]
            if last_word.endswith("m"):
                m_line_final += 1

    results["m_line_final_rate"] = m_line_final / max(1, m_total)

    # 2. Simple gallows at line[0] rate
    simple_gallows = {"t", "k", "p", "f"}
    gallows_at_start = 0
    gallows_total = 0
    for page in pages:
        for line in page.get("line_words", []):
            if not line:
                continue
            first_word = line[0]
            for ch in first_word:
                if ch in simple_gallows:
                    gallows_at_start += 1
            for word in line:
                for ch in word:
                    if ch in simple_gallows:
                        gallows_total += 1

    results["gallows_first_word_rate"] = (
        gallows_at_start / max(1, gallows_total)
    )

    # 3. Cross-boundary repeat rate
    n_boundaries = 0
    n_repeats = 0
    for page in pages:
        lines = page.get("line_words", [])
        for i in range(len(lines) - 1):
            if not lines[i] or not lines[i + 1]:
                continue
            n_boundaries += 1
            if lines[i][-1] == lines[i + 1][0]:
                n_repeats += 1

    results["cross_boundary_rate"] = n_repeats / max(1, n_boundaries)

    # 4. Section vocabulary specificity
    section_types: dict[str, set] = defaultdict(set)
    for page in pages:
        sec = page.get("section", "?")
        section_types[sec].update(page["words"])

    sections = [s for s in section_types if len(section_types[s]) >= 10]
    if len(sections) >= 2:
        overlaps = []
        for i in range(len(sections)):
            for j in range(i + 1, len(sections)):
                a = section_types[sections[i]]
                b = section_types[sections[j]]
                jaccard = len(a & b) / len(a | b) if (a | b) else 0
                overlaps.append(jaccard)
        results["section_jaccard_mean"] = float(np.mean(overlaps))
    else:
        results["section_jaccard_mean"] = None

    return results


def test_self_citation_structural(pages: list[dict],
                                   n_synth: int = N_SYNTH,
                                   seed: int = SEED) -> dict:
    """Generate synthetic self-citation corpora and compare structural properties."""
    real_measures = _measure_structural_properties(pages)

    null_measures: dict[str, list] = {k: [] for k in real_measures}

    for perm_i in range(n_synth):
        synth_pages = generate_self_citation_corpus(pages, seed=seed + perm_i)
        synth_measures = _measure_structural_properties(synth_pages)
        for k, v in synth_measures.items():
            null_measures[k].append(v)

    results = {}
    for prop, real_val in real_measures.items():
        nulls = [v for v in null_measures[prop] if v is not None]
        if not nulls:
            results[prop] = {
                "real": real_val, "reproduced": False,
                "reason": "no valid null samples",
            }
            continue

        null_mean = float(np.mean(nulls))
        null_std = float(np.std(nulls, ddof=1))
        z = _z_score(real_val, null_mean, null_std)

        reproduced = z is not None and abs(z) < 2.0
        results[prop] = {
            "real": round(real_val, 4) if real_val is not None else None,
            "null_mean": round(null_mean, 4),
            "null_std": round(null_std, 6) if null_std else None,
            "z_score": round(z, 2) if z is not None else None,
            "reproduced": reproduced,
        }

    n_repro = sum(1 for r in results.values() if r.get("reproduced"))
    n_total = len(results)

    return {
        "properties": results,
        "n_reproduced": n_repro,
        "n_total": n_total,
        "verdict": ("SELF-CITATION SUFFICIENT" if n_repro == n_total
                     else "SELF-CITATION INSUFFICIENT"),
    }


# =====================================================================
# DB persistence
# =====================================================================

def save_to_db(results: dict, db_path: Path) -> None:
    conn = sqlite3.connect(str(db_path))
    cur = conn.cursor()

    cur.execute("DROP TABLE IF EXISTS timm_test")
    cur.execute("""
        CREATE TABLE timm_test (
            test        TEXT,
            key         TEXT,
            observed    REAL,
            null_mean   REAL,
            null_std    REAL,
            z_score     REAL,
            detail_json TEXT,
            PRIMARY KEY (test, key)
        )
    """)

    def _insert(test: str, key: str, observed, null_mean=None,
                null_std=None, z_score=None, detail=None):
        cur.execute("INSERT INTO timm_test VALUES (?,?,?,?,?,?,?)",
                    (test, key, observed, null_mean, null_std, z_score,
                     json.dumps(detail) if detail else None))

    # 10a
    prox = results["proximity_clustering"]
    _insert("10a_proximity", "exact_match_rate",
            prox["observed"]["exact_match_proximity_rate"],
            prox.get("null_mean"), prox.get("null_std"),
            prox.get("z_score"), prox["observed"])

    # 10b
    decay = results["similarity_decay"]
    _insert("10b_decay", "correlation",
            decay.get("correlation_distance_similarity"),
            detail=decay)

    # 10c
    plocal = results["page_local_vocab"]
    _insert("10c_page_local", "ratio",
            plocal["observed"].get("ratio"),
            plocal.get("null_mean"), plocal.get("null_std"),
            plocal.get("z_score"), plocal["observed"])

    # 10d
    fw = results["first_word_repetition"]
    _insert("10d_first_word", "repetition_rate",
            fw["observed"]["first_word_repetition_rate"],
            fw.get("null_mean"), fw.get("null_std"),
            fw.get("z_score"), fw["observed"])

    # 10e
    struct = results["structural"]
    for prop, d in struct["properties"].items():
        _insert("10e_structural", prop,
                d.get("real"), d.get("null_mean"), d.get("null_std"),
                d.get("z_score"), d)

    conn.commit()
    conn.close()


# =====================================================================
# Console summary
# =====================================================================

def format_summary(results: dict) -> str:
    lines: list[str] = []
    lines.append("=" * 80)
    lines.append("  PHASE 10 — Timm (2014) self-citation test")
    lines.append("=" * 80)
    lines.append("")
    lines.append("  Timm claims text was generated by copying nearby words")
    lines.append("  and modifying them. No cipher, no language — just copying.")
    lines.append("  Bold claim: 'no VMS property contradicts self-citation.'")

    # 10a
    lines.append("\n-- 10a: Proximity clustering (Timm claims 91%) --")
    prox = results["proximity_clustering"]
    obs = prox["observed"]
    lines.append(f"  Exact-match proximity rate: {obs['exact_match_proximity_rate']:.1%} "
                 f"({obs['exact_match_n_pairs']} pairs)")
    lines.append(f"  Edit-dist proximity rate:   {obs['edit_distance_proximity_rate']:.1%} "
                 f"({obs['edit_distance_n_pairs']} pairs)")
    if prox.get("z_score") is not None:
        lines.append(f"  Null model: mean={prox['null_mean']:.1%}, "
                     f"z={prox['z_score']:+.2f}")
    lines.append(f"  Timm's claim: 91%")

    # 10b
    lines.append("\n-- 10b: Vocabulary similarity decay with distance --")
    decay = results["similarity_decay"]
    corr = decay.get("correlation_distance_similarity")
    lines.append(f"  Correlation (distance vs similarity): "
                 f"{corr:+.4f}" if corr is not None else "  n/a")
    if decay.get("sim_at_d1") and decay.get("sim_at_d20"):
        lines.append(f"  Similarity at d=1: {decay['sim_at_d1']:.4f}")
        lines.append(f"  Similarity at d=5: {decay.get('sim_at_d5', 'n/a')}")
        lines.append(f"  Similarity at d=20: {decay['sim_at_d20']:.4f}")
    if corr is not None and corr < -0.5:
        lines.append("  -> Strong decay: compatible with self-citation")
    elif corr is not None and corr < -0.2:
        lines.append("  -> Moderate decay: partially compatible")
    else:
        lines.append("  -> Weak/no decay: not compatible with self-citation")

    # 10c
    lines.append("\n-- 10c: Page-local vocabulary --")
    plocal = results["page_local_vocab"]
    pobs = plocal["observed"]
    lines.append(f"  Adjacent pages Jaccard:  {pobs['adjacent_jaccard_mean']:.4f}")
    lines.append(f"  Random pages Jaccard:    {pobs['random_jaccard_mean']:.4f}")
    lines.append(f"  Ratio (adj/random):      {pobs.get('ratio', 'n/a')}")
    if plocal.get("z_score") is not None:
        lines.append(f"  z-score vs null:         {plocal['z_score']:+.2f}")

    # 10d
    lines.append("\n-- 10d: First-word repetition --")
    fw = results["first_word_repetition"]
    fobs = fw["observed"]
    lines.append(f"  First-word repetition rate: {fobs['first_word_repetition_rate']:.1%} "
                 f"({fobs['n_repeated']}/{fobs['n_tested']})")
    if fw.get("z_score") is not None:
        lines.append(f"  Null model: mean={fw['null_mean']:.1%}, "
                     f"z={fw['z_score']:+.2f}")

    # 10e
    lines.append("\n-- 10e: Self-citation generator vs structural properties --")
    struct = results["structural"]
    lines.append(f"  {'Property':>25}  {'Real':>8}  {'SC_mean':>8}  {'z':>7}  {'Repro':>5}")
    lines.append("  " + "-" * 60)
    for prop, d in sorted(struct["properties"].items()):
        real = f"{d['real']:.4f}" if d.get("real") is not None else "   n/a"
        nm = f"{d['null_mean']:.4f}" if d.get("null_mean") is not None else "   n/a"
        z = f"{d['z_score']:+.2f}" if d.get("z_score") is not None else "  n/a"
        repro = "YES" if d.get("reproduced") else "NO"
        lines.append(f"  {prop:>25}  {real:>8}  {nm:>8}  {z:>7}  {repro:>5}")

    lines.append(f"\n  Reproduced: {struct['n_reproduced']}/{struct['n_total']}")
    lines.append(f"  Verdict: {struct['verdict']}")

    # Overall
    lines.append("\n-- Overall assessment --")
    v = results.get("overall_verdict", {})
    lines.append(f"  {v.get('summary', 'See details above')}")
    for point in v.get("findings", []):
        lines.append(f"    {point}")

    lines.append("\n" + "=" * 80)
    return "\n".join(lines) + "\n"


# =====================================================================
# Overall verdict
# =====================================================================

def compute_overall_verdict(results: dict) -> dict:
    """Synthesize evidence across all sub-tests."""
    findings: list[str] = []

    # 10a
    prox = results["proximity_clustering"]
    exact_rate = prox["observed"]["exact_match_proximity_rate"]
    z_prox = prox.get("z_score")
    if z_prox is not None and z_prox > 2:
        findings.append(
            f"Proximity clustering: {exact_rate:.0%} (z={z_prox:+.1f}). "
            "Significantly higher than null — self-citation signature PRESENT.")
    elif z_prox is not None:
        findings.append(
            f"Proximity clustering: {exact_rate:.0%} (z={z_prox:+.1f}). "
            "Not significantly above null — self-citation signature ABSENT.")

    # 10b
    corr = results["similarity_decay"].get("correlation_distance_similarity")
    if corr is not None and corr < -0.5:
        findings.append(f"Similarity decay: r={corr:+.3f} — strong, compatible with self-citation.")
    elif corr is not None:
        findings.append(f"Similarity decay: r={corr:+.3f} — weak/moderate.")

    # 10c
    plocal = results["page_local_vocab"]
    z_page = plocal.get("z_score")
    if z_page is not None and z_page > 2:
        findings.append(f"Page-local vocab: z={z_page:+.1f} — adjacent pages share more vocabulary.")
    elif z_page is not None:
        findings.append(f"Page-local vocab: z={z_page:+.1f} — not significant.")

    # 10d
    fw = results["first_word_repetition"]
    z_fw = fw.get("z_score")
    if z_fw is not None and z_fw > 2:
        findings.append(f"First-word repetition: z={z_fw:+.1f} — elevated, compatible with copying.")
    elif z_fw is not None:
        findings.append(f"First-word repetition: z={z_fw:+.1f} — not significant.")

    # 10e
    struct = results["structural"]
    n_repro = struct["n_reproduced"]
    n_total = struct["n_total"]

    # Compare with Markov (Phase 9f reproduced 1/4)
    findings.append(
        f"Structural properties: self-citation reproduces {n_repro}/{n_total} "
        f"(Markov reproduced ~1/4 in Phase 9f)."
    )

    # Summary
    signature_present = (z_prox is not None and z_prox > 2)
    struct_sufficient = (n_repro == n_total)

    if signature_present and struct_sufficient:
        summary = ("SELF-CITATION COMPATIBLE: the manuscript shows self-citation "
                   "signatures AND the mechanism reproduces all structural properties.")
    elif signature_present and not struct_sufficient:
        summary = (f"SELF-CITATION PARTIAL: self-citation signatures are present but "
                   f"the mechanism fails to reproduce {n_total - n_repro} structural "
                   f"properties. Self-citation alone is insufficient.")
    elif not signature_present:
        summary = ("SELF-CITATION SIGNATURES ABSENT: the manuscript does not show "
                   "significantly elevated proximity clustering vs null model.")
    else:
        summary = "INCONCLUSIVE"

    return {"summary": summary, "findings": findings}


# =====================================================================
# Entry point
# =====================================================================

def run(config: ToolkitConfig, force: bool = False, **kwargs) -> None:
    """Phase 10: Timm (2014) self-citation test."""
    report_path = config.stats_dir / "timm_test.json"
    summary_path = config.stats_dir / "timm_test_summary.txt"

    if report_path.exists() and not force:
        click.echo("  timm_test report exists. Use --force to re-run.")
        return

    config.ensure_dirs()
    print_header("PHASE 10 — Timm (2014) Self-Citation Test")

    # 1. Parse corpus
    print_step("Parsing EVA corpus...")
    eva_file = config.eva_data_dir / "LSI_ivtff_0d.txt"
    if not eva_file.exists():
        raise click.ClickException(f"EVA file not found: {eva_file}")
    eva_data = parse_eva_words(eva_file)
    pages = eva_data["pages"]
    click.echo(f"    {eva_data['total_words']:,} words, {len(pages)} pages")

    # Also parse IVTFF lines for line-level tests
    print_step("Parsing IVTFF lines...")
    all_lines = parse_ivtff_lines(eva_file)
    content_lines = [l for l in all_lines
                     if l.get("para_type") != "label" and l.get("words")]

    # Add section info to lines (from pages)
    folio_section = {}
    for p in pages:
        folio_section[p["folio"]] = p.get("section", "?")
    for line in content_lines:
        line["section"] = folio_section.get(line["folio"], "?")

    click.echo(f"    {len(content_lines)} content lines")

    # 2. Test 10a: Proximity clustering
    print_step("10a: Proximity clustering...")
    prox_obs = test_proximity_clustering(content_lines)
    click.echo(f"    Exact-match: {prox_obs['exact_match_proximity_rate']:.1%} "
               f"({prox_obs['exact_match_n_pairs']} pairs)")
    click.echo(f"    Edit-dist:   {prox_obs['edit_distance_proximity_rate']:.1%} "
               f"({prox_obs['edit_distance_n_pairs']} pairs)")

    print_step("10a: Null model (500 permutations)...")
    prox_null = null_proximity_clustering(content_lines, n_perms=N_NULL, seed=SEED)
    z_prox = _z_score(prox_obs["exact_match_proximity_rate"],
                       prox_null["null_mean"], prox_null["null_std"])
    click.echo(f"    Null: mean={prox_null['null_mean']:.1%}, "
               f"z={z_prox:+.2f}" if z_prox is not None else "    z=n/a")

    proximity_results = {
        "observed": prox_obs,
        "null_mean": prox_null["null_mean"],
        "null_std": prox_null["null_std"],
        "z_score": round(z_prox, 2) if z_prox is not None else None,
    }

    # 3. Test 10b: Similarity decay
    print_step("10b: Vocabulary similarity decay...")
    decay_results = test_similarity_decay(content_lines)
    corr = decay_results.get("correlation_distance_similarity")
    click.echo(f"    Correlation: {corr:+.4f}" if corr else "    n/a")

    # 4. Test 10c: Page-local vocabulary
    print_step("10c: Page-local vocabulary...")
    plocal_obs = test_page_local_vocab(pages)
    if not plocal_obs.get("skipped"):
        click.echo(f"    Adjacent: {plocal_obs['adjacent_jaccard_mean']:.4f}, "
                   f"Random: {plocal_obs['random_jaccard_mean']:.4f}")

        print_step("10c: Null model (500 permutations)...")
        plocal_null = null_page_local_vocab(pages, n_perms=N_NULL, seed=SEED)
        z_page = _z_score(plocal_obs.get("ratio", 1.0),
                           plocal_null["null_mean"], plocal_null["null_std"])
        click.echo(f"    z={z_page:+.2f}" if z_page is not None else "    z=n/a")
    else:
        plocal_null = {"null_mean": 0, "null_std": 0}
        z_page = None

    page_local_results = {
        "observed": plocal_obs,
        "null_mean": plocal_null["null_mean"],
        "null_std": plocal_null["null_std"],
        "z_score": round(z_page, 2) if z_page is not None else None,
    }

    # 5. Test 10d: First-word repetition
    print_step("10d: First-word repetition...")
    fw_obs = test_first_word_repetition(content_lines)
    click.echo(f"    Rate: {fw_obs['first_word_repetition_rate']:.1%}")

    print_step("10d: Null model (500 permutations)...")
    fw_null = null_first_word_repetition(content_lines, n_perms=N_NULL, seed=SEED)
    z_fw = _z_score(fw_obs["first_word_repetition_rate"],
                     fw_null["null_mean"], fw_null["null_std"])
    click.echo(f"    Null: mean={fw_null['null_mean']:.1%}, "
               f"z={z_fw:+.2f}" if z_fw is not None else "    z=n/a")

    fw_results = {
        "observed": fw_obs,
        "null_mean": fw_null["null_mean"],
        "null_std": fw_null["null_std"],
        "z_score": round(z_fw, 2) if z_fw is not None else None,
    }

    # 6. Test 10e: Self-citation generator
    print_step("10e: Self-citation generator (50 synthetic corpora)...")
    structural_results = test_self_citation_structural(pages, n_synth=N_SYNTH, seed=SEED)
    click.echo(f"    Reproduced: {structural_results['n_reproduced']}/"
               f"{structural_results['n_total']}")
    click.echo(f"    Verdict: {structural_results['verdict']}")

    # 7. Overall verdict
    print_step("Computing overall verdict...")
    all_results = {
        "proximity_clustering": proximity_results,
        "similarity_decay": decay_results,
        "page_local_vocab": page_local_results,
        "first_word_repetition": fw_results,
        "structural": structural_results,
    }
    overall = compute_overall_verdict(all_results)
    all_results["overall_verdict"] = overall
    click.echo(f"    {overall['summary']}")

    # 8. Save
    print_step("Saving JSON...")
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)
    click.echo(f"    {report_path}")

    summary = format_summary(all_results)
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(summary)
    click.echo(f"    {summary_path}")

    print_step("Writing DB table timm_test...")
    db_path = config.output_dir.parent / "voynich.db"
    if db_path.exists():
        save_to_db(all_results, db_path)
        click.echo(f"    {db_path}")
    else:
        click.echo(f"    WARN: DB not found at {db_path}")

    click.echo(f"\n{summary}")
